/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMatchRouteImport } from './routes/_app/match'
import { Route as AppJoinRouteImport } from './routes/_app/join'
import { Route as AppGigsRouteImport } from './routes/_app/gigs'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppAmbassadorRouteImport } from './routes/_app/ambassador'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppLabIndexRouteImport } from './routes/_app/lab.index'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups.index'
import { Route as AppCirclesIndexRouteImport } from './routes/_app/circles.index'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppOnboardingTenantRouteImport } from './routes/_app/onboarding.tenant'
import { Route as AppLiveSessionIdRouteImport } from './routes/_app/live.$sessionId'
import { Route as AppLabProjectIdRouteImport } from './routes/_app/lab.$projectId'
import { Route as AppInviteTokenRouteImport } from './routes/_app/invite.$token'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups.$groupId'
import { Route as AppCirclesNewRouteImport } from './routes/_app/circles.new'
import { Route as AppCirclesDiscoverRouteImport } from './routes/_app/circles.discover'
import { Route as AppCirclesCircleIdRouteImport } from './routes/_app/circles.$circleId'
import { Route as AppGroupsInviteTokenRouteImport } from './routes/_app/groups.invite.$token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAmbassadorRoute = AppAmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLabIndexRoute = AppLabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesIndexRoute = AppCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingTenantRoute = AppOnboardingTenantRouteImport.update({
  id: '/onboarding/tenant',
  path: '/onboarding/tenant',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveSessionIdRoute = AppLiveSessionIdRouteImport.update({
  id: '/live/$sessionId',
  path: '/live/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppLabProjectIdRoute = AppLabProjectIdRouteImport.update({
  id: '/lab/$projectId',
  path: '/lab/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteTokenRoute = AppInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesNewRoute = AppCirclesNewRouteImport.update({
  id: '/circles/new',
  path: '/circles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesDiscoverRoute = AppCirclesDiscoverRouteImport.update({
  id: '/circles/discover',
  path: '/circles/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesCircleIdRoute = AppCirclesCircleIdRouteImport.update({
  id: '/circles/$circleId',
  path: '/circles/$circleId',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsInviteTokenRoute = AppGroupsInviteTokenRouteImport.update({
  id: '/groups/invite/$token',
  path: '/groups/invite/$token',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/ambassador': typeof AppAmbassadorRoute
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/gigs': typeof AppGigsRoute
  '/join': typeof AppJoinRoute
  '/match': typeof AppMatchRoute
  '/messages': typeof AppMessagesRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/circles/discover': typeof AppCirclesDiscoverRoute
  '/circles/new': typeof AppCirclesNewRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/lab/$projectId': typeof AppLabProjectIdRoute
  '/live/$sessionId': typeof AppLiveSessionIdRoute
  '/onboarding/tenant': typeof AppOnboardingTenantRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/circles/': typeof AppCirclesIndexRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/lab/': typeof AppLabIndexRoute
  '/groups/invite/$token': typeof AppGroupsInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/ambassador': typeof AppAmbassadorRoute
  '/events': typeof AppEventsRoute
  '/feed': typeof AppFeedRoute
  '/gigs': typeof AppGigsRoute
  '/join': typeof AppJoinRoute
  '/match': typeof AppMatchRoute
  '/messages': typeof AppMessagesRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/circles/discover': typeof AppCirclesDiscoverRoute
  '/circles/new': typeof AppCirclesNewRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/invite/$token': typeof AppInviteTokenRoute
  '/lab/$projectId': typeof AppLabProjectIdRoute
  '/live/$sessionId': typeof AppLiveSessionIdRoute
  '/onboarding/tenant': typeof AppOnboardingTenantRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/circles': typeof AppCirclesIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/lab': typeof AppLabIndexRoute
  '/groups/invite/$token': typeof AppGroupsInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ambassador': typeof AppAmbassadorRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/gigs': typeof AppGigsRoute
  '/_app/join': typeof AppJoinRoute
  '/_app/match': typeof AppMatchRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/_app/circles/discover': typeof AppCirclesDiscoverRoute
  '/_app/circles/new': typeof AppCirclesNewRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/invite/$token': typeof AppInviteTokenRoute
  '/_app/lab/$projectId': typeof AppLabProjectIdRoute
  '/_app/live/$sessionId': typeof AppLiveSessionIdRoute
  '/_app/onboarding/tenant': typeof AppOnboardingTenantRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/circles/': typeof AppCirclesIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/lab/': typeof AppLabIndexRoute
  '/_app/groups/invite/$token': typeof AppGroupsInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/ambassador'
    | '/events'
    | '/feed'
    | '/gigs'
    | '/join'
    | '/match'
    | '/messages'
    | '/requests'
    | '/settings'
    | '/circles/$circleId'
    | '/circles/discover'
    | '/circles/new'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/lab/$projectId'
    | '/live/$sessionId'
    | '/onboarding/tenant'
    | '/profile/$userId'
    | '/circles/'
    | '/groups/'
    | '/lab/'
    | '/groups/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/ambassador'
    | '/events'
    | '/feed'
    | '/gigs'
    | '/join'
    | '/match'
    | '/messages'
    | '/requests'
    | '/settings'
    | '/circles/$circleId'
    | '/circles/discover'
    | '/circles/new'
    | '/groups/$groupId'
    | '/invite/$token'
    | '/lab/$projectId'
    | '/live/$sessionId'
    | '/onboarding/tenant'
    | '/profile/$userId'
    | '/circles'
    | '/groups'
    | '/lab'
    | '/groups/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_app/admin'
    | '/_app/ambassador'
    | '/_app/events'
    | '/_app/feed'
    | '/_app/gigs'
    | '/_app/join'
    | '/_app/match'
    | '/_app/messages'
    | '/_app/requests'
    | '/_app/settings'
    | '/_app/circles/$circleId'
    | '/_app/circles/discover'
    | '/_app/circles/new'
    | '/_app/groups/$groupId'
    | '/_app/invite/$token'
    | '/_app/lab/$projectId'
    | '/_app/live/$sessionId'
    | '/_app/onboarding/tenant'
    | '/_app/profile/$userId'
    | '/_app/circles/'
    | '/_app/groups/'
    | '/_app/lab/'
    | '/_app/groups/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join': {
      id: '/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ambassador': {
      id: '/_app/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AppAmbassadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab/': {
      id: '/_app/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof AppLabIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/': {
      id: '/_app/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof AppCirclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/tenant': {
      id: '/_app/onboarding/tenant'
      path: '/onboarding/tenant'
      fullPath: '/onboarding/tenant'
      preLoaderRoute: typeof AppOnboardingTenantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/$sessionId': {
      id: '/_app/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof AppLiveSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab/$projectId': {
      id: '/_app/lab/$projectId'
      path: '/lab/$projectId'
      fullPath: '/lab/$projectId'
      preLoaderRoute: typeof AppLabProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite/$token': {
      id: '/_app/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AppInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/new': {
      id: '/_app/circles/new'
      path: '/circles/new'
      fullPath: '/circles/new'
      preLoaderRoute: typeof AppCirclesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/discover': {
      id: '/_app/circles/discover'
      path: '/circles/discover'
      fullPath: '/circles/discover'
      preLoaderRoute: typeof AppCirclesDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles/$circleId': {
      id: '/_app/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof AppCirclesCircleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/invite/$token': {
      id: '/_app/groups/invite/$token'
      path: '/groups/invite/$token'
      fullPath: '/groups/invite/$token'
      preLoaderRoute: typeof AppGroupsInviteTokenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAmbassadorRoute: typeof AppAmbassadorRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGigsRoute: typeof AppGigsRoute
  AppJoinRoute: typeof AppJoinRoute
  AppMatchRoute: typeof AppMatchRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCirclesCircleIdRoute: typeof AppCirclesCircleIdRoute
  AppCirclesDiscoverRoute: typeof AppCirclesDiscoverRoute
  AppCirclesNewRoute: typeof AppCirclesNewRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppInviteTokenRoute: typeof AppInviteTokenRoute
  AppLabProjectIdRoute: typeof AppLabProjectIdRoute
  AppLiveSessionIdRoute: typeof AppLiveSessionIdRoute
  AppOnboardingTenantRoute: typeof AppOnboardingTenantRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppCirclesIndexRoute: typeof AppCirclesIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppLabIndexRoute: typeof AppLabIndexRoute
  AppGroupsInviteTokenRoute: typeof AppGroupsInviteTokenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAmbassadorRoute: AppAmbassadorRoute,
  AppEventsRoute: AppEventsRoute,
  AppFeedRoute: AppFeedRoute,
  AppGigsRoute: AppGigsRoute,
  AppJoinRoute: AppJoinRoute,
  AppMatchRoute: AppMatchRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCirclesCircleIdRoute: AppCirclesCircleIdRoute,
  AppCirclesDiscoverRoute: AppCirclesDiscoverRoute,
  AppCirclesNewRoute: AppCirclesNewRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppInviteTokenRoute: AppInviteTokenRoute,
  AppLabProjectIdRoute: AppLabProjectIdRoute,
  AppLiveSessionIdRoute: AppLiveSessionIdRoute,
  AppOnboardingTenantRoute: AppOnboardingTenantRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppCirclesIndexRoute: AppCirclesIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppLabIndexRoute: AppLabIndexRoute,
  AppGroupsInviteTokenRoute: AppGroupsInviteTokenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
