/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMatchRouteImport } from './routes/_app/match'
import { Route as AppLabRouteImport } from './routes/_app/lab'
import { Route as AppGigsRouteImport } from './routes/_app/gigs'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppCirclesRouteImport } from './routes/_app/circles'
import { Route as AppAmbassadorRouteImport } from './routes/_app/ambassador'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppLabProjectIdRouteImport } from './routes/_app/lab.$projectId'
import { Route as AppCirclesCircleIdRouteImport } from './routes/_app/circles.$circleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppAmbassadorRoute = AppAmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppLabProjectIdRoute = AppLabProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppLabRoute,
} as any)
const AppCirclesCircleIdRoute = AppCirclesCircleIdRouteImport.update({
  id: '/$circleId',
  path: '/$circleId',
  getParentRoute: () => AppCirclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ambassador': typeof AppAmbassadorRoute
  '/circles': typeof AppCirclesRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/gigs': typeof AppGigsRoute
  '/lab': typeof AppLabRouteWithChildren
  '/match': typeof AppMatchRoute
  '/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/lab/$projectId': typeof AppLabProjectIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ambassador': typeof AppAmbassadorRoute
  '/circles': typeof AppCirclesRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/gigs': typeof AppGigsRoute
  '/lab': typeof AppLabRouteWithChildren
  '/match': typeof AppMatchRoute
  '/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/lab/$projectId': typeof AppLabProjectIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/ambassador': typeof AppAmbassadorRoute
  '/_app/circles': typeof AppCirclesRouteWithChildren
  '/_app/feed': typeof AppFeedRoute
  '/_app/gigs': typeof AppGigsRoute
  '/_app/lab': typeof AppLabRouteWithChildren
  '/_app/match': typeof AppMatchRoute
  '/_app/circles/$circleId': typeof AppCirclesCircleIdRoute
  '/_app/lab/$projectId': typeof AppLabProjectIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/ambassador'
    | '/circles'
    | '/feed'
    | '/gigs'
    | '/lab'
    | '/match'
    | '/circles/$circleId'
    | '/lab/$projectId'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ambassador'
    | '/circles'
    | '/feed'
    | '/gigs'
    | '/lab'
    | '/match'
    | '/circles/$circleId'
    | '/lab/$projectId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/ambassador'
    | '/_app/circles'
    | '/_app/feed'
    | '/_app/gigs'
    | '/_app/lab'
    | '/_app/match'
    | '/_app/circles/$circleId'
    | '/_app/lab/$projectId'
    | '/_app/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ambassador': {
      id: '/_app/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AppAmbassadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab/$projectId': {
      id: '/_app/lab/$projectId'
      path: '/$projectId'
      fullPath: '/lab/$projectId'
      preLoaderRoute: typeof AppLabProjectIdRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/circles/$circleId': {
      id: '/_app/circles/$circleId'
      path: '/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof AppCirclesCircleIdRouteImport
      parentRoute: typeof AppCirclesRoute
    }
  }
}

interface AppCirclesRouteChildren {
  AppCirclesCircleIdRoute: typeof AppCirclesCircleIdRoute
}

const AppCirclesRouteChildren: AppCirclesRouteChildren = {
  AppCirclesCircleIdRoute: AppCirclesCircleIdRoute,
}

const AppCirclesRouteWithChildren = AppCirclesRoute._addFileChildren(
  AppCirclesRouteChildren,
)

interface AppLabRouteChildren {
  AppLabProjectIdRoute: typeof AppLabProjectIdRoute
}

const AppLabRouteChildren: AppLabRouteChildren = {
  AppLabProjectIdRoute: AppLabProjectIdRoute,
}

const AppLabRouteWithChildren =
  AppLabRoute._addFileChildren(AppLabRouteChildren)

interface AppRouteChildren {
  AppAmbassadorRoute: typeof AppAmbassadorRoute
  AppCirclesRoute: typeof AppCirclesRouteWithChildren
  AppFeedRoute: typeof AppFeedRoute
  AppGigsRoute: typeof AppGigsRoute
  AppLabRoute: typeof AppLabRouteWithChildren
  AppMatchRoute: typeof AppMatchRoute
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmbassadorRoute: AppAmbassadorRoute,
  AppCirclesRoute: AppCirclesRouteWithChildren,
  AppFeedRoute: AppFeedRoute,
  AppGigsRoute: AppGigsRoute,
  AppLabRoute: AppLabRouteWithChildren,
  AppMatchRoute: AppMatchRoute,
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
