-- Skipped on replay: demo-user seed referencing tenant_id UUIDs that were
-- created ad hoc in the original live database and never captured in a
-- migration, so the FK target doesn't exist on a fresh replay.
-- No schema changes in this file.
